### ISSUE TITLE
모바일 환경에서 뒤로 가기 버튼 클릭 시 화면 가리는 문제 

### ISSUE THREAD

**Issue by bexoss** [iamport/iamport-react-example#2]
모바일 + 이니시스 웹표준 결제창 기준이고요, 
React 환경에서 웹표준 결제창 띄우고 
사용자가 '취소하기' 버튼이 아니라 '뒤로가기' 버튼을 누르면, 
아임포트에서 띄운 iframe 이 화면 전체를 가려버리는 현상 있습니다. 
해결되어야 하지 않을까요?
크롬 개발자 도구로 휴대폰 화면 띄워놓고 해도 쉽게 재현할 수 있습니다.

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

말씀하신 버그를 수정해 반영하였습니다.
고객님의 가맹점 식별코드에 대해 정상 동작하는 것을 확인하였습니다.

그동안 이용에 불편함이 많으셨으리라 생각합니다.
저희쪽에서 대응이 매우 늦어 대단히 죄송합니다.

추가적인 이슈 발생하시면 문의주세요.
최대한 빠르게 팔로우업 하도록 하겠습니다.

감사합니다.

**Comment by bexoss** [comment]
노고에 감사드립니다.
