### ISSUE TITLE
리다이렉트 URL 질문

### ISSUE THREAD

**Issue by nuno1111** [iamport/iamport-react-example#9]
## 원래 URL에서 결제요청 후 결제 취소나..결제 완료 리턴되는 URL이.. 항상 65자리로 잘립니다.

- 원 URL :                 https://finder.xpanner.com:8001/#/finder/mchown/paymentInfo/PAY-0000000000000052
- 결제 후 리턴 URL : https://finder.xpanner.com:8001/#/finder/mchown/paymentInfo/PAY-

혹시 원인이나 조치방법 안내 가능하실까요?

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

support@iamport.kr로 동일 문의 주시어 답변 완료된 것으로 확인되므로 해당 이슈는 close 하도록 하겠습니다.

추가적으로 궁금하신 사항 있으시면 언제든지 문의주세요!
감사합니다.
